### ISSUE TITLE
AttributeError: 'module' object has no attribute '_create_unverified_context' Ubuntu 14.04.4

### ISSUE THREAD

**Issue by knalbone** [jalavoy/pfsense-backup#1]
I receive the following error on Ubuntu 14.04.4:
`AttributeError: 'module' object has no attribute '_create_unverified_context'`

Looks like this is due python 2.7.6 being the installed version on Ubuntu 14.04.4. SSLContext was introduced in 2.7.9.

**Comment by jalavoy** [comment]
It looks like i'd have to rewrite this completely to work around the problem. I think using the PPA to get 2.7.9+ is a better method.

I've updated the readme with this information. Apologies for the inconvenience.
